# Generated by Django 5.0.1 on 2024-02-06 23:29

import django.db.models.deletion
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaProducto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(auto_now=True, verbose_name='Fecha de borrado')),
                ('descripción', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria de Producto',
                'verbose_name_plural': 'Categorias de Productos',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(auto_now=True, verbose_name='Fecha de borrado')),
                ('descripción', models.CharField(max_length=50, unique=True, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Unidad de Medida',
                'verbose_name_plural': 'Unidads de Medidas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalCategoriaProducto',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(blank=True, editable=False, verbose_name='Fecha de borrado')),
                ('descripción', models.CharField(db_index=True, max_length=50, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Categoria de Producto',
                'verbose_name_plural': 'historical Categorias de Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalUnidadMedida',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(blank=True, editable=False, verbose_name='Fecha de borrado')),
                ('descripción', models.CharField(db_index=True, max_length=50, verbose_name='Descripción')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Unidad de Medida',
                'verbose_name_plural': 'historical Unidads de Medidas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(auto_now=True, verbose_name='Fecha de borrado')),
                ('producto', models.CharField(max_length=150, unique=True, verbose_name='Producto')),
                ('descripción_producto', models.TextField(unique=True, verbose_name='Descripción del producto')),
                ('categoria_producto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.categoriaproducto', verbose_name='Categoria del producto')),
                ('unidad_medida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='productos.unidadmedida', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(auto_now_add=True, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(auto_now=True, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(auto_now=True, verbose_name='Fecha de borrado')),
                ('valor_descuento', models.PositiveSmallIntegerField(default=0)),
                ('categoria_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='productos.unidadmedida', verbose_name='Indicador de Oferta')),
            ],
            options={
                'verbose_name': 'Indicaor de Oferta',
                'verbose_name_plural': 'Indicador de Ofertas',
            },
        ),
        migrations.CreateModel(
            name='HistoricalProducto',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(blank=True, editable=False, verbose_name='Fecha de borrado')),
                ('producto', models.CharField(db_index=True, max_length=150, verbose_name='Producto')),
                ('descripción_producto', models.TextField(db_index=True, verbose_name='Descripción del producto')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('categoria_producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.categoriaproducto', verbose_name='Categoria del producto')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unidad_medida', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.unidadmedida', verbose_name='Unidad de medida')),
            ],
            options={
                'verbose_name': 'historical Producto',
                'verbose_name_plural': 'historical Productos',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalIndicador',
            fields=[
                ('id', models.IntegerField(blank=True, db_index=True)),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('frcha_creacion', models.DateField(blank=True, editable=False, verbose_name='Fecha de creacion')),
                ('fecha_modificado', models.DateField(blank=True, editable=False, verbose_name='Fecha de modificacion')),
                ('fecha_borrado', models.DateField(blank=True, editable=False, verbose_name='Fecha de borrado')),
                ('valor_descuento', models.PositiveSmallIntegerField(default=0)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('categoria_producto', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='productos.unidadmedida', verbose_name='Indicador de Oferta')),
            ],
            options={
                'verbose_name': 'historical Indicaor de Oferta',
                'verbose_name_plural': 'historical Indicador de Ofertas',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
