# Generated by Django 5.0.1 on 2024-02-07 02:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalproducto',
            old_name='descripción_producto',
            new_name='descripcion_producto',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='descripción_producto',
            new_name='descripcion_producto',
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='precio',
            field=models.FloatField(default=10, max_length=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='producto_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='producto_comprado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de comprado'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='producto_modificado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de modificado'),
        ),
        migrations.AddField(
            model_name='historicalproducto',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
        migrations.AddField(
            model_name='producto',
            name='precio',
            field=models.FloatField(default=10.0, max_length=10, verbose_name='Precio'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_agregado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de agregado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_comprado',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de comprado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='producto_modificado',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de modificado'),
        ),
        migrations.AddField(
            model_name='producto',
            name='vendido',
            field=models.BooleanField(default=False, verbose_name='Vendido'),
        ),
    ]
